### PR TITLE
Added name option

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Hello,
Me again there ;)
I happened to need to set the device name when advertising my beacon.
This patch addresses this.

@don  @sandeepmistry

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@beaufortfrancois this looks good to me! @don what do you think?

One note the name option won't work on OS X, as the CoreBluetooth hack bleno uses doesn't support scan response data, just advertisement. So we should add a note about it somewhere.

**Comment by beaufortfrancois** [comment]
I didn't try this but shouldn't this be working for Mac OS?

``` objective-c
NSString * baconName = [[UIDevice currentDevice] name];
NSDictionary *advertisementData = @{CBAdvertisementDataServiceUUIDsKey:@[[CBUUIDUUIDWithString:BACON_SERVICE_UUID]],
CBAdvertisementDataLocalNameKey:baconName};
```

**Comment by sandeepmistry** [comment]
@beaufortfrancois bleno uses the super secret `kCBAdvDataAppleMfgData` advertisement data key, value is type buffer. This allows us to add service data along with the service UUID in the advertisement packet. We could try to squeeze the name into the advertisement packet, but there is a 31 byte limit.

**Comment by beaufortfrancois** [comment]
Does CoreBluetooth has "super secret" scan response data we could use?

**Comment by sandeepmistry** [comment]
@beaufortfrancois not that I'm aware of, I used the following command the determine `kCBAdvDataAppleMfgData`:

``` sh
strings /usr/sbin/blued | grep kCBAdv
```

**Pull request merged**
